# Generated by Django 3.2.4 on 2021-06-24 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
